version: '3.8'

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    expose:
      - 6379

  app:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"